### ISSUE TITLE
General Review & Feedback

### ISSUE THREAD

**Issue by andrewrreed** [fastforwardlabs/analyzing_headlines_with_spacy#2]
# General Review & Feedback

Overall, this is great - concise, clean, and informative! Here are a few minor suggestions broken out by section:

## In the README.md
- In the first sentence, maybe include the "formal" name of the task (NER) vs. just entity extraction. 
  - So: "The notebook in this repo demonstrates its use _for the task of Named Entity Recognition (NER)_ on a real world news dataset."
- I've never seen the _Github Issue comment --> image link_ trick before, and I like it. However, given that this repo will hopefully become an AMP at some point, and therefore make the jump to the Cloudera Github org, it might be best to include it in an `/images` directory at the root of project so the content doesn't somehow get lost along the way.

## In the notebook
- Maybe include an H2 title above the imports that says "Setup Project Dependencies" or something of the like. Not necessary, but provides logical starting point for code relative to introduction blurb and maintains visual consistency with rest of notebook.

### Extract entities with spaCy
- Did you develop this locally or on CDSW? When I test on `fflab-4`, I get the following error with `spacy.load('en_core_web_sm')`, but it does load fine as an independent package...
![image](https://user-images.githubusercontent.com/23462538/101213488-74cbf180-3648-11eb-8c9e-072b983d353b.png)
- I really like the final explanation in this section that starts with _"So thin why should we use a statistical model..."_

### Timeline of mentions for a named entity
- I think you are missing the phrase *occurence plot* at the end of the intro sentence.

### Organization co-occurrence matrix
- Leveraging a trick learned from Mike Lee Williams at the Jupyter notebook brownbag - utilize the `;` character after a plot to suppress matplotlib jargon (<AxesSubplot:xlabel='Entity', ylabel='Entity'>)
```
_, ax = plt.subplots(figsize=(10,10))
sns.heatmap(no_zeros > 0, cmap='Blues', ax=ax);
```
- Also, maybe add a title to the heat map for clarity..

## Possible extension or follow on notebook

While reading through this notebook, it seems the natural progression and next step for an end user would be the desire to build a model for their own organizations entities. A cool follow on to this notebook would be a walkthrough of all considerations needed to train a custom NER model - data collection/annotation, model training (in spaCy?), evaluation of performance... A bit more involved than this one, but I think it would be super useful and widely applicable content. I'll add this to my backlog of AMP ideas...

**Comment by cjwallace** [comment]
Thanks @andrewrreed. Agree with all comments, willfix. In particular:

- Good call on the image directory.
- I did develop on the ffl cluster, but I didn't hit that problem with `en_core_web_sm`. However, I _did_ hit it when I tried the large model. I hear there is some [jankiness](https://github.com/explosion/spaCy/issues/4577) with model loading in notebooks, and I wanted to see if someone else ran into it during test. Congratulations, it you! I'll replace with the direct model import.
- On the extension, the answer I would probably recommend to folks is "buy and use [prodi.gy](https://prodi.gy/)" (having not actually used it myself). Do you have thoughts on the usefulness of demonstrations of paid products with CML? Trouble is we couldn't distribute a license. Probably the right approach would be show a MVP version in streamlit or dash or whatever, but bear in mind there are pro tools for data labeling if someone wants to do this robustly at any scale.

**Comment by cjwallace** [comment]
Fixed and awaiting second review at your convenience @andrewrreed. I don't think there's any urgency until we have a way to lift notebooks to AMPs, though perhaps we can use this as a first example of doing so (or else Victor's explainability notebooks).

**Comment by andrewrreed** [comment]
Ahh - I was unaware of prodi.gy! Just took a quick look and I see why you would recommend that - looks like a great tool that (cleanly) covers the bases I was imagining for the extension notebook...

Given that, I do think it would be tough for us to promote and demo a licensed product. Plus, there are probably some legal considerations for Cloudera to do so. If anything, we could maybe include a quick blurb at the end of your notebook that has a short discussion to address the idea of training a custom NER model and suggest prodi.gy as a strong tool for doing so? Either way, I don't feel too strong about this..

**Comment by cjwallace** [comment]
I like that idea. How about extending the final section to this?

>## To spaCy and beyond
>Hopefully, this notebook has inspired your own use cases for named entity recognition. NER is but one mature NLP capability, for which spaCy provides industrial strength tooling. Even without training our own model, we were able to prototype a couple of capabilities that might be the basis of tools for use by journalists, businesses, or national statistics organisations seeking to monitor company activity.
>
>If we had been working with a more esoteric dataset, or wanted better entity recognition on our particular dataset, or desired different categories of entity, we could fine tune a model for the purpose. Doing so would require that we have data labeled with examples of the entities we want to extract. We could label that manually, employ a commercial labeling service, or use a purpose built tool like [prodi.gy](https://prodi.gy) (from the makers of spaCy).

**Comment by andrewrreed** [comment]
That looks great! Just re-tested the notebook on CDSW and everything runs fine.

**Only update needed:** The link to the NER.png in the README.md currently does not render on CDSW/CML's "Overview" page. Looks like you just need to drop the leading `/`.

(/docs/images/NER.png) --> (docs/images/NER.png)

**Comment by cjwallace** [comment]
Closing this since changes have been made and the review is complete.
